# Generated by Django 4.1 on 2022-08-22 11:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0002_rename_noti_temp_profile_noti_tempo"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("record", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="detail",
            name="duration",
        ),
        migrations.RemoveField(
            model_name="detail",
            name="focus",
        ),
        migrations.RemoveField(
            model_name="detail",
            name="profile",
        ),
        migrations.AddField(
            model_name="detail",
            name="user",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="detail",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="room",
            name="user",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="room",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="detail",
            name="end_focus",
            field=models.DateField(auto_now=True),
        ),
        migrations.AlterField(
            model_name="detail",
            name="room",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="detail",
                to="record.room",
            ),
        ),
        migrations.AlterField(
            model_name="room",
            name="profile",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="room",
                to="user.profile",
            ),
        ),
    ]
