# Generated by Django 4.1 on 2022-08-25 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("record", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="room",
            name="end_time",
            field=models.DateTimeField(auto_now=True),
        ),
    ]
