# Generated by Django 4.1 on 2022-08-25 09:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
    ]

    operations = [
        migrations.CreateModel(
            name="Profile",
            fields=[
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        primary_key=True,
                        serialize=False,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                ("nickname", models.CharField(default="user", max_length=128)),
                ("photo_tempo", models.IntegerField(default=10)),
                ("notification", models.BooleanField(default=True)),
                ("noti_tempo", models.IntegerField(default=10)),
                (
                    "image",
                    models.ImageField(default="/media/default.png", upload_to=""),
                ),
            ],
        ),
    ]
