# Generated by Django 4.1 on 2022-08-19 08:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="profile",
            old_name="noti_temp",
            new_name="noti_tempo",
        ),
    ]
