# Generated by Django 4.1 on 2022-08-20 07:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0002_rename_noti_temp_profile_noti_tempo"),
        ("record", "0002_detail_user_room_user_alter_detail_end_focus_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="detail",
            old_name="room",
            new_name="rid",
        ),
        migrations.AlterField(
            model_name="detail",
            name="profile",
            field=models.ForeignKey(
                db_column="RID",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="detail",
                to="user.profile",
            ),
        ),
        migrations.AlterField(
            model_name="room",
            name="end_time",
            field=models.DateField(auto_now=True),
        ),
    ]
