# Generated by Django 4.1 on 2022-08-20 07:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("record", "0003_rename_room_detail_rid_alter_detail_profile_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="detail",
            name="duration",
            field=models.DurationField(null=True),
        ),
        migrations.AlterField(
            model_name="detail",
            name="rid",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="detail",
                to="record.room",
            ),
        ),
    ]
