# Generated by Django 4.1 on 2022-08-20 08:07

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0002_rename_noti_temp_profile_noti_tempo"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("record", "0004_alter_detail_duration_alter_detail_rid"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Room",
            new_name="Party",
        ),
        migrations.RenameField(
            model_name="detail",
            old_name="rid",
            new_name="pid",
        ),
        migrations.RenameField(
            model_name="party",
            old_name="RID",
            new_name="PID",
        ),
        migrations.RemoveField(
            model_name="detail",
            name="focus",
        ),
        migrations.RemoveField(
            model_name="detail",
            name="profile",
        ),
        migrations.RemoveField(
            model_name="detail",
            name="user",
        ),
    ]
