# Generated by Django 4.1 on 2022-08-20 08:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("record", "0005_rename_room_party_rename_rid_detail_pid_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="detail",
            name="duration",
        ),
    ]
