# Generated by Django 4.1 on 2022-08-20 17:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("record", "0009_alter_detail_end_focus_alter_detail_start_focus_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="party",
            name="profile",
        ),
    ]
